### PR TITLE
Support for Theta Value in Smart Contracts

### PR DESCRIPTION
**Pull request by jieyilong**

### CODE REVIEW

**Comment by Webhero9297** [comment]
Hello JieyiLong
Is this the way for staking theta token in the smart contracts?
If yes, could you let me know how to stake theta token in the smart contract?
And I've read this news online.
Is wrapped $theta coming soon really?
If you answer me, I will be very happy.
Thanks

**Comment by Jacob021** [comment]
> Hello JieyiLong
> Is this the way for staking theta token in the smart contracts?
> If yes, could you let me know how to stake theta token in the smart contract?
> And I've read this news online.
> Is wrapped $theta coming soon really?
> If you answer me, I will be very happy.
> Thanks

Hello, kindly provide your email address so we can contact you and guide you on how to stake your theta tokens on smart contract

**Comment by Webhero9297** [comment]
Thank you Jacob021
THis is my email address.
weblock9297@gmail.com
Please support me.
Thanks

**Comment by jieyilong** [comment]
> Hello JieyiLong Is this the way for staking theta token in the smart contracts? If yes, could you let me know how to stake theta token in the smart contract? And I've read this news online. Is wrapped $theta coming soon really? If you answer me, I will be very happy. Thanks

Staking Theta through smart contract is NOT supported yet. Please be aware of scammers that claim they can help you with staking through smart contract. When wrapped THETA is available we will announce it through the official channels.

**Comment by Webhero9297** [comment]
> > Hello JieyiLong Is this the way for staking theta token in the smart contracts? If yes, could you let me know how to stake theta token in the smart contract? And I've read this news online. Is wrapped $theta coming soon really? If you answer me, I will be very happy. Thanks
> 
> Staking Theta through smart contract is NOT supported yet. Please be aware of scammers that claim they can help you with staking through smart contract. When wrapped THETA is available we will announce it through the official channels.

Well, when may I expect the time of launch wtheta in the official channel?
Thanks

**Comment by Webhero9297** [comment]
I would like to get one piece of advice from you.
In fact, I already had a decision to make WTHETA tokens for a long time, but it was impossible without your help.
In other words, I would like to get help from you for the following functions for THETA token
#1: deposit and withdraw theta token in the smart contracts
#2: staking theta token from the smart contract to the guardian node directly.
(I've seen example code for the staking theta token to guardian node in the thetajs library. But I want this feature in the smart contract.)
I would like to ask for your help in this regard.
In fact, I have not been able to participate in Theta Hackathon twice because I could not implement this function.
I want to launch my theta blockchain DeFi project asap.
Thanks

**Comment by Webhero9297** [comment]
Dear @jieyilong 
Thanks for your efforts. Could you provide me with the way how to use the above feature in Solidity? I want to learn about that from you now. Thanks

**Pull request merged**
